User.create(name: "Jan", password: "password")
User.create(name: "Jin", password: "password")
User.create(name: "Jun", password: "password")
User.create(name: "Jen", password: "password")
User.create(name: "Jon", password: "password")